version: '3.3'
services:
  app:
    build: .
    image: ${DOCKER_IMAGE}
    restart: always
    networks:
      - servicenet
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - docker_jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7:ro
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:/usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:ro
      - /tmp/jenkins:/tmp/jenkins
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources:
        limits:
          cpus: '1.5'
          memory: 2000M
        reservations:
          cpus: '1.0'
          memory: 1500M
      restart_policy:
        condition: any
        delay: 5s
        window: 120s

  nonpriv_proxy:
    image: registry.osslabs.net/nonpriv-proxy:7da6f46-master
    restart: always
    labels:
      com.openslate.service_ip: ${SERVICE_IP}/24
    networks:
      - hostnet
    environment:
      - SERVICE_IP
      - SERVICE_PORT
      - VAULT_ADDR
      - VAULT_CERTIFICATE_PATH=/v1/secret/ssl/star.osslabs.net
      - VAULT_TOKEN
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      restart_policy:
        condition: any
        delay: 5s
        window: 120s


networks:
  servicenet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}

  hostnet:
    external:
      name: host


volumes:
  docker_jenkins_home:
    external:
      name: docker-jenkins-home
