version: '3.4'
services:
  app:
    build: ..
    image: ${DOCKER_IMAGE}
    restart: always
    environment:
      - JAVA_OPTS
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - docker_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/jenkins:/tmp/jenkins
