version: '3.4'
services:
  app:
    build: ..
    image: ${DOCKER_IMAGE}
    restart: always
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    volumes:
      - docker_jenkins_home:/var/jenkins_home
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7:ro
      - /usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:/usr/lib/x86_64-linux-gnu/libltdl.so.7.3.1:ro
