rbac.create: true

persistence.storageClass: default-ebs
persistence.size: ${MASTER_VOLUME_SIZE}

master.tag: "2.190"

# AWS IAM role for backup S3 upload
master.podAnnotations.iam\.amazonaws\.com/role: JenkinsBackup

{% if '${CF_ENV}' == 'staging' %}
master.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: spot
master.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: DoesNotExist
{% else %}
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: 1
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].key: spot
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: DoesNotExist
{% endif %}

master.serviceType: ClusterIP
master.ingress.enabled: true
master.ingress.hostName: ${INGRESS_HOST}
master.ingress.annotations.zalando\.org/aws-load-balancer-scheme: internal

master.resources.requests.cpu: 500m
master.resources.requests.memory: 3Gi
master.resources.limits.cpu: 2000m
master.resources.limits.memory: 4Gi

master.javaOpts: -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dorg.jenkinsci.plugins.github_branch_source.GitHubSCMSource.cacheSize=0

{% set plugins -%}
ace-editor:1.1
analysis-core:1.96
analysis-model-api:5.3.0
ansicolor:0.6.2
ant:1.9
antisamy-markup-formatter:1.5
apache-httpcomponents-client-4-api:4.5.5-3.0
authentication-tokens:1.3
aws-java-sdk:1.11.594
basic-branch-build-strategies:1.3.2
blueocean:1.18.1
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.18.1
blueocean-commons:1.18.1
blueocean-config:1.18.1
blueocean-core-js:1.18.1
blueocean-dashboard:1.18.1
blueocean-display-url:2.3.0
blueocean-events:1.18.1
blueocean-git-pipeline:1.18.1
blueocean-github-pipeline:1.18.1
blueocean-i18n:1.18.1
blueocean-jira:1.18.1
blueocean-jwt:1.18.1
blueocean-personalization:1.18.1
blueocean-pipeline-api-impl:1.18.1
blueocean-pipeline-editor:1.18.1
blueocean-pipeline-scm-api:1.18.1
blueocean-rest:1.18.1
blueocean-rest-impl:1.18.1
blueocean-web:1.18.1
bouncycastle-api:2.17
branch-api:2.5.4
browserstack-integration:1.1.3
build-timeout:1.19
cloudbees-bitbucket-branch-source:2.4.5
cloudbees-folder:6.9
cobertura:1.14
code-coverage-api:1.0.13
command-launcher:1.3
config-file-provider:3.6.2
copyartifact:1.42.1
credentials:2.2.1
credentials-binding:1.20
display-url-api:2.3.2
docker-commons:1.15
docker-workflow:1.19
durable-task:1.30
email-ext:2.66
envinject:2.2.0
envinject-api:1.6
external-monitor-job:1.7
favorite:2.3.2
git:3.12.0
git-client:2.8.0
git-server:1.8
github:1.29.4
github-api:1.95
github-branch-source:2.5.6
github-pr-coverage-status:2.0.0
gradle:1.33
handlebars:1.1.1
handy-uri-templates-2-api:2.1.7-1.0
htmlpublisher:1.18
jackson2-api:2.9.9.1
javadoc:1.5
jdk-tool:1.3
jenkins-design-language:1.18.1
jira:3.0.9
jquery:1.12.4-1
jquery-detached:1.2.1
jquery-ui:1.0.2
jsch:0.1.55.1
junit:1.28
kubernetes:1.18.1
kubernetes-credentials:0.4.1
ldap:1.20
lockable-resources:2.5
mailer:1.24
mapdb-api:1.0.9.0
matrix-auth:2.4.2
matrix-project:1.14
maven-plugin:3.4
mercurial:2.8
metrics:4.0.2.5
momentjs:1.1.1
pam-auth:1.5.1
pipeline-build-step:2.9
pipeline-github:2.5
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.10
pipeline-milestone-step:1.3.1
pipeline-model-api:1.3.9
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.3.9
pipeline-model-extensions:1.3.9
pipeline-rest-api:2.12
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.3.9
pipeline-stage-view:2.12
plain-credentials:1.5
prometheus:2.0.0
publish-over:0.22
pubsub-light:1.13
resource-disposer:0.13
role-strategy:2.13
s3:0.11.2
scm-api:2.6.3
script-security:1.62
slack:2.32
sse-gateway:1.19
ssh-agent:1.17
ssh-credentials:1.17.1
ssh-slaves:1.30.1
structs:1.20
subversion:2.12.2
swarm:3.17
timestamper:1.10
token-macro:2.8
trilead-api:1.0.5
variant:1.3
warnings:5.0.1
warnings-ng:5.3.0
windows-slaves:1.4
workflow-aggregator:2.6
workflow-api:2.36
workflow-basic-steps:2.18
workflow-cps:2.73
workflow-cps-global-lib:2.15
workflow-durable-task-step:2.33
workflow-job:2.34
workflow-multibranch:2.21
workflow-scm-step:2.9
workflow-step-api:2.20
workflow-support:3.3
ws-cleanup:0.37
{% endset %}

{% for plugin in plugins.strip().split('\n') %}
master.installPlugins[{{ loop.index - 1 }}]: {{ plugin }}
{% endfor%}
