rbac.create: true

persistence.storageClass: default-ebs
persistence.size: ${MASTER_VOLUME_SIZE}

master.tag: "2.229"

# AWS IAM role for backup S3 upload
master.podAnnotations.iam\.amazonaws\.com/role: JenkinsBackup

{% if '${CF_ENV}' == 'staging' %}
master.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: spot
master.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: DoesNotExist
{% else %}
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: 1
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].key: spot
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: DoesNotExist
{% endif %}

master.serviceType: ClusterIP
master.ingress.enabled: true
master.ingress.hostName: ${INGRESS_HOST}
master.ingress.annotations.zalando\.org/aws-load-balancer-scheme: internal

master.resources.requests.cpu: 500m
master.resources.requests.memory: 3Gi
master.resources.limits.cpu: 2000m
master.resources.limits.memory: 4Gi

master.javaOpts: -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dorg.jenkinsci.plugins.github_branch_source.GitHubSCMSource.cacheSize=0

{% set plugins -%}
ace-editor:1.1
analysis-core:1.96
analysis-model-api:8.0.1
ansicolor:0.6.3
ant:1.11
antisamy-markup-formatter:2.0
apache-httpcomponents-client-4-api:4.5.10-2.0
authentication-tokens:1.3
aws-java-sdk:1.11.723
basic-branch-build-strategies:1.3.2
blueocean:1.22.0
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.22.0
blueocean-commons:1.22.0
blueocean-config:1.22.0
blueocean-core-js:1.22.0
blueocean-dashboard:1.22.0
blueocean-display-url:2.3.1
blueocean-events:1.22.0
blueocean-git-pipeline:1.22.0
blueocean-github-pipeline:1.22.0
blueocean-i18n:1.22.0
blueocean-jira:1.22.0
blueocean-jwt:1.22.0
blueocean-personalization:1.22.0
blueocean-pipeline-api-impl:1.22.0
blueocean-pipeline-editor:1.22.0
blueocean-pipeline-scm-api:1.22.0
blueocean-rest:1.22.0
blueocean-rest-impl:1.22.0
blueocean-web:1.22.0
bootstrap4-api:4.4.1-11
bouncycastle-api:2.18
branch-api:2.5.5
browserstack-integration:1.1.3
build-timeout:1.19.1
cloudbees-bitbucket-branch-source:2.7.0
cloudbees-folder:6.11.1
cobertura:1.16
code-coverage-api:1.1.4
command-launcher:1.4
config-file-provider:3.6.3
copyartifact:1.43.1
credentials:2.3.5
credentials-binding:1.21
data-tables-api:1.10.20-14
display-url-api:2.3.2
docker-commons:1.16
docker-workflow:1.23
durable-task:1.34
echarts-api:4.6.0-8
email-ext:2.69
envinject:2.3.0
envinject-api:1.7
external-monitor-job:1.7
favorite:2.3.2
font-awesome-api:5.13.0-1
forensics-api:0.7.0
git:4.2.2
git-client:3.2.1
git-server:1.9
github:1.29.5
github-api:1.106
github-branch-source:2.6.0
github-pr-coverage-status:2.1.1
google-oauth-plugin:1.0.0
gradle:1.36
handlebars:1.1.1
handy-uri-templates-2-api:2.1.8-1.0
hashicorp-vault-plugin:3.2.0
htmlpublisher:1.22
jackson2-api:2.10.3
javadoc:1.5
jdk-tool:1.4
jenkins-design-language:1.22.0
jira:3.0.14
jquery:1.12.4-1
jquery-detached:1.2.1
jquery-ui:1.0.2
jquery3-api:3.4.1-10
jsch:0.1.55.2
junit:1.28
kubernetes-client-api:4.8.0-1
kubernetes-credentials:0.6.2
ldap:1.22
lockable-resources:2.7
mailer:1.30
mapdb-api:1.0.9.0
matrix-auth:2.5
matrix-project:1.14
maven-plugin:3.5
mercurial:2.8
metrics:4.0.2.6
momentjs:1.1.1
oauth-credentials:0.4
pam-auth:1.6
pipeline-build-step:2.12
pipeline-github:2.5
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.11
pipeline-milestone-step:1.3.1
pipeline-model-api:1.6.0
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.6.0
pipeline-model-extensions:1.6.0
pipeline-rest-api:2.13
pipeline-stage-step:2.3
pipeline-stage-tags-metadata:1.6.0
pipeline-stage-view:2.13
plain-credentials:1.7
plugin-util-api:1.0.2
popper-api:1.16.0-6
prometheus:2.0.6
publish-over:0.22
pubsub-light:1.13
resource-disposer:0.14
role-strategy:2.16
s3:0.11.5
scm-api:2.6.3
script-security:1.71
slack:2.37
sse-gateway:1.23
ssh-agent:1.19
ssh-credentials:1.18.1
ssh-slaves:1.31.1
structs:1.20
subversion:2.13.1
swarm:3.19
timestamper:1.11.2
token-macro:2.12
trilead-api:1.0.6
variant:1.3
warnings:5.0.1
warnings-ng:8.1.0
windows-slaves:1.6
workflow-aggregator:2.6
workflow-api:2.40
workflow-basic-steps:2.19
workflow-cps:2.80
workflow-cps-global-lib:2.16
workflow-durable-task-step:2.35
workflow-job:2.38
workflow-multibranch:2.21
workflow-scm-step:2.10
workflow-step-api:2.22
workflow-support:3.4
ws-cleanup:0.38
{% endset %}

{% for plugin in plugins.strip().split('\n') %}
master.installPlugins[{{ loop.index - 1 }}]: {{ plugin }}
{% endfor%}
