rbac.create: true

persistence.storageClass: default-ebs
persistence.size: ${MASTER_VOLUME_SIZE}

master.tag: "2.265"

# AWS IAM role for backup S3 upload
master.podAnnotations.iam\.amazonaws\.com/role: JenkinsBackup

{% if '${CF_ENV}' == 'staging' %}
master.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: spot
master.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: DoesNotExist
{% else %}
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: 1
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].key: spot
master.affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: DoesNotExist
{% endif %}

master.serviceType: ClusterIP
master.ingress.enabled: true
master.ingress.hostName: ${INGRESS_HOST}
master.ingress.annotations.zalando\.org/aws-load-balancer-scheme: internal

master.resources.requests.cpu: 500m
master.resources.requests.memory: 3Gi
master.resources.limits.cpu: 2000m
master.resources.limits.memory: 4Gi

master.javaOpts: -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dorg.jenkinsci.plugins.github_branch_source.GitHubSCMSource.cacheSize=0

{% set plugins -%}
ace-editor:1.1
analysis-core:1.96
analysis-model-api:9.3.1
ansicolor:0.7.3
ant:1.11
antisamy-markup-formatter:2.1
apache-httpcomponents-client-4-api:4.5.10-2.0
authentication-tokens:1.4
aws-java-sdk:1.11.854
basic-branch-build-strategies:1.3.2
blueocean:1.24.3
blueocean-autofavorite:1.2.4
blueocean-bitbucket-pipeline:1.24.3
blueocean-commons:1.24.3
blueocean-config:1.24.3
blueocean-core-js:1.24.3
blueocean-dashboard:1.24.3
blueocean-display-url:2.4.0
blueocean-events:1.24.3
blueocean-git-pipeline:1.24.3
blueocean-github-pipeline:1.24.3
blueocean-i18n:1.24.3
blueocean-jira:1.24.3
blueocean-jwt:1.24.3
blueocean-personalization:1.24.3
blueocean-pipeline-api-impl:1.24.3
blueocean-pipeline-editor:1.24.3
blueocean-pipeline-scm-api:1.24.3
blueocean-rest:1.24.3
blueocean-rest-impl:1.24.3
blueocean-web:1.24.3
bootstrap4-api:4.5.3-1
bouncycastle-api:2.18
branch-api:2.6.1
browserstack-integration:1.1.8
build-timeout:1.20
checks-api:1.1.0
cloudbees-bitbucket-branch-source:2.9.4
cloudbees-disk-usage-simple:0.10
cloudbees-folder:6.14
cobertura:1.16
code-coverage-api:1.2.0
command-launcher:1.5
config-file-provider:3.7.0
copyartifact:1.45.2
credentials:2.3.13
credentials-binding:1.24
data-tables-api:1.10.21-3
display-url-api:2.3.3
docker-commons:1.17
docker-workflow:1.24
durable-task:1.35
echarts-api:4.9.0-2
email-ext:2.79
envinject:2.3.0
envinject-api:1.7
extended-read-permission:3.2
external-monitor-job:1.7
favorite:2.3.2
font-awesome-api:5.15.1-1
forensics-api:0.7.0
git:4.4.5
git-client:3.5.1
git-server:1.9
github:1.32.0
github-api:1.116
github-branch-source:2.9.1
github-pr-coverage-status:2.1.1
google-oauth-plugin:1.0.2
gradle:1.36
handlebars:1.1.1
handy-uri-templates-2-api:2.1.8-1.0
hashicorp-vault-plugin:3.6.1
htmlpublisher:1.23
jackson2-api:2.11.3
javadoc:1.6
jdk-tool:1.4
jenkins-design-language:1.24.3
jira:3.1.3
jquery:1.12.4-1
jquery-detached:1.2.1
jquery-ui:1.0.2
jquery3-api:3.5.1-2
jsch:0.1.55.2
junit:1.43
kubernetes:1.27.5
kubernetes-client-api:4.11.1
kubernetes-credentials:0.7.0
ldap:1.25
lockable-resources:2.10
mailer:1.32.1
mapdb-api:1.0.9.0
matrix-auth:2.6.4
matrix-project:1.18
maven-plugin:3.8
mercurial:2.12
metrics:4.0.2.6
momentjs:1.1.1
oauth-credentials:0.4
okhttp-api:3.14.9
pam-auth:1.6
pipeline-build-step:2.13
pipeline-github:2.7
pipeline-github-lib:1.0
pipeline-graph-analysis:1.10
pipeline-input-step:2.12
pipeline-milestone-step:1.3.1
pipeline-model-api:1.7.2
pipeline-model-declarative-agent:1.1.1
pipeline-model-definition:1.7.2
pipeline-model-extensions:1.7.2
pipeline-rest-api:2.18
pipeline-stage-step:2.5
pipeline-stage-tags-metadata:1.7.2
pipeline-stage-view:2.18
plain-credentials:1.7
plugin-util-api:1.4.0
popper-api:1.16.0-7
prometheus:2.0.8
publish-over:0.22
pubsub-light:1.13
resource-disposer:0.14
role-strategy:3.1
s3:0.11.5
scm-api:2.6.4
script-security:1.75
slack:2.43
snakeyaml-api:1.27.0
sse-gateway:1.24
ssh-agent:1.20
ssh-credentials:1.18.1
ssh-slaves:1.31.2
structs:1.20
subversion:2.13.2
swarm:3.24
timestamper:1.11.8
token-macro:2.12
trilead-api:1.0.12
variant:1.3
warnings:5.0.2
warnings-ng:8.4.4
windows-slaves:1.6
workflow-aggregator:2.6
workflow-api:2.40
workflow-basic-steps:2.21
workflow-cps:2.84
workflow-cps-global-lib:2.17
workflow-durable-task-step:2.35
workflow-job:2.40
workflow-multibranch:2.22
workflow-scm-step:2.11
workflow-step-api:2.23
workflow-support:3.6
ws-cleanup:0.38
{% endset %}

{% for plugin in plugins.strip().split('\n') %}
master.installPlugins[{{ loop.index - 1 }}]: {{ plugin }}
{% endfor%}
