rbac.install: true

Persistence.StorageClass: default-ebs
Persistence.Size: 20Gi

Master.ImageTag: "2.170"

{% if '${CF_ENV}' == 'staging' %}
Master.Affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: spot
Master.Affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].operator: DoesNotExist
{% else %}
Master.Affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].weight: 1
Master.Affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].key: spot
Master.Affinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].preference.matchExpressions[0].operator: DoesNotExist
{% endif %}

Master.ServiceType: ClusterIP
Master.HostName: ${INGRESS_HOST}
Master.ingress.enabled: true
Master.ingress.hostName: ${INGRESS_HOST}
Master.ingress.annotations.zalando\.org/aws-load-balancer-scheme: internal

Master.resources.requests.cpu: 500m
Master.resources.requests.memory: 3Gi
Master.resources.limits.cpu: 2000m
Master.resources.limits.memory: 4Gi

Master.JavaOpts: -Dhudson.slaves.NodeProvisioner.initialDelay=0 -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85 -Dorg.jenkinsci.plugins.github_branch_source.GitHubSCMSource.cacheSize=0

{% set plugins -%}
pipeline-stage-tags-metadata:1.3.4.1
blueocean-dashboard:1.10.2
blueocean-rest:1.10.2
analysis-model-api:2.0.2
pipeline-model-definition:1.3.4.1
javadoc:1.4
pipeline-github-lib:1.0
blueocean-config:1.10.2
pipeline-build-step:2.7
matrix-auth:2.3
favorite:2.3.2
basic-branch-build-strategies:1.1.1
git:3.9.2
junit:1.26.1
build-timeout:1.19
authentication-tokens:1.3
blueocean-git-pipeline:1.10.2
jsch:0.1.55
pipeline-rest-api:2.10
command-launcher:1.3
momentjs:1.1.1
blueocean-bitbucket-pipeline:1.10.2
git-client:2.7.6
blueocean-events:1.10.2
workflow-step-api:2.18
blueocean-personalization:1.10.2
jdk-tool:1.2
kubernetes-credentials:0.4.0
pipeline-input-step:2.9
pubsub-light:1.12
jenkins-design-language:1.10.2
mailer:1.23
github-branch-source:2.4.2
blueocean-rest-impl:1.10.2
browserstack-integration:1.1.3
blueocean-pipeline-api-impl:1.10.2
timestamper:1.8.10
display-url-api:2.3.0
slack:2.14
email-ext:2.63
script-security:1.51
handy-uri-templates-2-api:2.1.6-1.0
ssh-slaves:1.29.4
matrix-project:1.13
pipeline-model-api:1.3.4.1
workflow-aggregator:2.6
blueocean-commons:1.10.2
workflow-job:2.31
cloudbees-folder:6.7
ant:1.9
blueocean-autofavorite:1.2.3
token-macro:2.6
blueocean-jira:1.10.2
ace-editor:1.1
durable-task:1.28
credentials:2.1.18
pipeline-model-extensions:1.3.4.1
pam-auth:1.4
docker-commons:1.13
git-server:1.7
lockable-resources:2.4
pipeline-model-declarative-agent:1.1.1
htmlpublisher:1.18
pipeline-milestone-step:1.3.1
swarm:3.15
pipeline-stage-view:2.10
resource-disposer:0.12
cloudbees-bitbucket-branch-source:2.4.0
ssh-agent:1.17
plain-credentials:1.5
github:1.29.3
workflow-support:3.1
envinject-api:1.5
ansicolor:0.6.1
ldap:1.20
envinject:2.1.6
bouncycastle-api:2.17
pipeline-graph-analysis:1.9
workflow-cps:2.62
blueocean-github-pipeline:1.10.2
blueocean:1.10.2
blueocean-core-js:1.10.2
workflow-durable-task-step:2.28
config-file-provider:3.5
kubernetes:1.14.3
maven-plugin:3.2
blueocean-display-url:2.2.0
trilead-api:1.0.1
subversion:2.12.1
cobertura:1.13
jira:3.0.5
docker-workflow:1.17
analysis-core:1.95
apache-httpcomponents-client-4-api:4.5.5-3.0
blueocean-i18n:1.10.2
scm-api:2.3.0
workflow-multibranch:2.20
workflow-scm-step:2.7
gradle:1.30
github-pr-coverage-status:2.0.0
github-api:1.95
role-strategy:2.9.0
blueocean-jwt:1.10.2
blueocean-pipeline-editor:1.10.2
workflow-cps-global-lib:2.12
workflow-basic-steps:2.14
credentials-binding:1.17
variant:1.1
mapdb-api:1.0.9.0
warnings-ng:2.1.2
pipeline-stage-step:2.3
jackson2-api:2.9.8
ws-cleanup:0.37
publish-over:0.22
handlebars:1.1.1
mercurial:2.5
branch-api:2.1.2
ssh-credentials:1.14
workflow-api:2.33
blueocean-web:1.10.2
sse-gateway:1.17
antisamy-markup-formatter:1.5
blueocean-pipeline-scm-api:1.10.2
jquery-detached:1.2.1
pipeline-github:2.1
structs:1.17
warnings:5.0.1
code-coverage-api:1.0.7
{% endset %}

{% for plugin in plugins.strip().split('\n') %}
Master.InstallPlugins[{{ loop.index - 1 }}]: {{ plugin }}
{% endfor%}
