apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/prometheus"
    external-dns.alpha.kubernetes.io/hostname: ${PUBLIC_URL}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
    service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-67df3c08,sg-7451a01b
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:488926586334:certificate/1801cf37-963b-4fe3-a6c1-927a841664dd
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    io.cattle.field/appId: jenkins
  name: public-jenkins
  namespace: jenkins
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    io.cattle.field/appId: jenkins
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 185.199.108.0/22
  - 192.30.252.0/22
